#!/bin/bash

VZLIST=/usr/sbin/vzlist
VZCTL=/usr/sbin/vzctl

while read VZ 
do
	if [ "$VZ" != "VEID STATUS" ]
	then
		RUNNING=`echo $VZ | grep running`	
		if [ -z "$RUNNING" ]
		then
			$VZCTL start $VZ
		fi
	fi	
done < <($VZLIST -a -o veid,status)
